// <auto-generated />
using System;
using AgendaIR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgendaIR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgendaIR.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("AgendaIR.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("MagicToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TokenGeradoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("MagicToken")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AgendaIR.Models.DocumentoAnexado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("ConteudoComprimido")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DocumentoSolicitadoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TamanhoComprimidoBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("TamanhoOriginalBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("DocumentoSolicitadoId");

                    b.ToTable("DocumentosAnexados");
                });

            modelBuilder.Entity("AgendaIR.Models.DocumentoSolicitado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DocumentosSolicitados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(488),
                            Descricao = "Envie o RG frente e verso em um único arquivo PDF ou imagem",
                            Nome = "RG (Frente e Verso)",
                            Obrigatorio = true
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(491),
                            Descricao = "Envie uma cópia do CPF",
                            Nome = "CPF",
                            Obrigatorio = true
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(493),
                            Descricao = "Conta de luz, água ou telefone dos últimos 3 meses",
                            Nome = "Comprovante de Residência",
                            Obrigatorio = true
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(506),
                            Descricao = "Informe de rendimentos do ano anterior",
                            Nome = "Informe de Rendimentos",
                            Obrigatorio = false
                        });
                });

            modelBuilder.Entity("AgendaIR.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GoogleCalendarEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GoogleCalendarToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CPF = "000.000.000-00",
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(69),
                            Email = "admin@agendair.com",
                            IsAdmin = true,
                            Nome = "Administrador do Sistema",
                            SenhaHash = "$2a$11$.7N/rN4z8a0pNrocFXzu7.mnmB7IbBNeoPRG/bbfwkQ7QeXMV3G8.",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AgendaIR.Models.TipoAgendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposAgendamento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(574),
                            Descricao = "Declaração de Imposto de Renda",
                            Nome = "Declaração IR"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(576),
                            Descricao = "Retificação de declaração de IR",
                            Nome = "Declaração IR Retificadora"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(578),
                            Descricao = "Consultoria sobre questões tributárias",
                            Nome = "Consultoria Tributária"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(579),
                            Descricao = "Abertura de Microempreendedor Individual",
                            Nome = "Abertura de MEI"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(580),
                            Descricao = "Serviços contábeis mensais",
                            Nome = "Contabilidade Mensal"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(581),
                            Descricao = "Regularização de pendências fiscais",
                            Nome = "Regularização Fiscal"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(583),
                            Descricao = "Planejamento estratégico tributário",
                            Nome = "Planejamento Tributário"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 1, 23, 20, 21, 52, 861, DateTimeKind.Utc).AddTicks(584),
                            Descricao = "Outros serviços",
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("AgendaIR.Models.Agendamento", b =>
                {
                    b.HasOne("AgendaIR.Models.Cliente", "Cliente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgendaIR.Models.Funcionario", "Funcionario")
                        .WithMany("Agendamentos")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("AgendaIR.Models.Cliente", b =>
                {
                    b.HasOne("AgendaIR.Models.Funcionario", "Funcionario")
                        .WithMany("Clientes")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("AgendaIR.Models.DocumentoAnexado", b =>
                {
                    b.HasOne("AgendaIR.Models.Agendamento", "Agendamento")
                        .WithMany("DocumentosAnexados")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaIR.Models.DocumentoSolicitado", "DocumentoSolicitado")
                        .WithMany("DocumentosAnexados")
                        .HasForeignKey("DocumentoSolicitadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("DocumentoSolicitado");
                });

            modelBuilder.Entity("AgendaIR.Models.Agendamento", b =>
                {
                    b.Navigation("DocumentosAnexados");
                });

            modelBuilder.Entity("AgendaIR.Models.Cliente", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("AgendaIR.Models.DocumentoSolicitado", b =>
                {
                    b.Navigation("DocumentosAnexados");
                });

            modelBuilder.Entity("AgendaIR.Models.Funcionario", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
